x-common: &default
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: '10m'
  environment: &default-environment
    TZ: Asia/Shanghai

services:
  efb-wechat:
    <<: *default
    container_name: efb-wechat
    image: j0k3rh/efb-wechat
    network_mode: host
    volumes:
      - ./data:/data
