token: "your telegram bot token"
admins:
- your telegram id
flags:
    # 关闭自动语言设置，使用 systemd 启动时默认中文
    auto_locale: false
    animated_stickers: true
# request_kwargs:
    # 配置 http 代理
    # proxy_url: http://PROXY_HOST:PROXY_PORT/
    # Optional, if you need authentication:
    # username: PROXY_USER
    # password: PROXY_PASS