token: "your telgram token"
admins:
- your telgram id
flags:
    # 关闭自动语言设置，使用 systemd 启动时默认中文
    auto_locale: false
    animated_stickers: true
    delete_on_edit: true
    send_stickers_and_gif_as_jpeg: true